version: "2"

services:
  s3:
    image: docker.io/localstack/localstack:0.8.8
    container_name: s3
    ports:
      - 4572:4572
    environment:
      - SERVICES=s3
      - DEBUG=true
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8080
    networks:
      - default
    mem_limit: 512m

  tika:
    image: docker.io/smalswebtech/tika-server:latest
    container_name: tika
    networks:
      - default
    mem_limit: 512m

  postgresql:
    image: docker.io/postgres:9.6
    container_name: postgresql
    environment:
      - POSTGRES_USER=${BATS_ROOT_DB_USER}
      - POSTGRES_PASSWORD=${BATS_ROOT_DB_PASSWORD}
      - POSTGRES_DB=${BATS_ROOT_DB_NAME}
    volumes:
      - data_pgsql:/var/lib/postgresql/data
    networks:
      - default
    mem_limit: 512m

  elasticms:
    image: ${BATS_EMS_DOCKER_IMAGE_NAME}
    container_name: ems
    ports:
      - 9000:9000
    environment:
      - AWS_S3_STORAGE_BUCKET_NAME=${BATS_S3_STORAGE_BUCKET_NAME}
      - AWS_S3_CONFIG_BUCKET_NAME=${BATS_S3_CONFIG_BUCKET_NAME}
      - AWS_S3_ENDPOINT_URL=${BATS_S3_ENDPOINT_URL}
      - AWS_ACCESS_KEY_ID=${BATS_S3_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${BATS_S3_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${BATS_S3_DEFAULT_REGION}
      - PHP_FPM_MAX_CHILDREN=${BATS_PHP_FPM_MAX_CHILDREN}
      - PHP_FPM_REQUEST_MAX_MEMORY_IN_MEGABYTES=${BATS_PHP_FPM_REQUEST_MAX_MEMORY_IN_MEGABYTES}
      - CONTAINER_HEAP_PERCENT=${BATS_CONTAINER_HEAP_PERCENT}
      - ES_ENDPOINT_URL=${BATS_ES_LOCAL_ENDPOINT_URL}
      - TIKA_ENDPOINT_URL=${BATS_TIKA_LOCAL_ENDPOINT_URL}
      - DB_DRIVER=${BATS_DB_DRIVER}
      - DB_HOST=${BATS_DB_HOST}
      - DB_PORT=${BATS_DB_PORT}
      - DB_USER=${BATS_DB_USER}
      - DB_PASSWORD=${BATS_DB_PASSWORD}
      - DB_NAME=${BATS_DB_NAME}
      - REDIS_HOST=${BATS_REDIS_HOST}
      - REDIS_PORT=${BATS_REDIS_PORT}
    links:
      - ${BATS_STORAGE_SERVICE_NAME}:${BATS_STORAGE_SERVICE_NAME}
      - s3:s3
    depends_on:
      - ${BATS_STORAGE_SERVICE_NAME}
      - s3
    command: ["wait-for-it", "${BATS_DB_HOST}:${BATS_DB_PORT}", "--", "/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
    networks:
      - default
    build:
      context: .
      args:
        VERSION_ARG: ${ELASTICMS_VERSION}
        RELEASE_ARG: ${RELEASE_NUMBER}
        BUILD_DATE_ARG: ${BUILD_DATE}
        VCS_REF_ARG: ${VCS_REF}
    mem_limit: 512m

  elasticsearch_1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.11
    container_name: elasticsearch_1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
      - "discovery.zen.minimum_master_nodes=1"
    volumes:
      - data_es_1:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - default
    mem_limit: 1024m

  elasticsearch_2:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.11
    container_name: elasticsearch_2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch_1"
      - "xpack.security.enabled=false"
      - "discovery.zen.minimum_master_nodes=1"
    volumes:
      - data_es_2:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - default
    mem_limit: 1024m

  redis:
    image: centos/redis-5-centos7
    container_name: redis
    volumes:
      - data_redis:/var/lib/redis/data
    networks:
      - default
    mem_limit: 512m

volumes:
  data_redis:
    external:
      name: ${BATS_REDIS_VOLUME_NAME}
  data_pgsql:
    external:
      name: ${BATS_PGSQL_VOLUME_NAME}
  data_es_1:
    external:
      name: ${BATS_ES_1_VOLUME_NAME}
  data_es_2:
    external:
      name: ${BATS_ES_2_VOLUME_NAME}
  clair_config:
    external:
      name: ${BATS_CLAIR_LOCAL_SCANNER_CONFIG_VOLUME_NAME}

networks:
  default:
    external:
      name: docker_default
